### ISSUE TITLE
#359 breaks existing Kitchen configurations

### ISSUE THREAD

**Issue by chewi** [sous-chefs/postgresql-cookbook#377]
I already stated this in #359 but I guess it got missed because it was closed and now the newest release includes this breakage.

The changed seems pointless. It worked fine in Chef Zero before because, unlike Chef Solo, it does have somewhere to store the data, under /tmp/kitchen/nodes. Now existing users will be inconvenienced so please revert it.

**Comment by patcon** [comment]
Agreed. Left a comment on the commit as well: https://github.com/sous-chefs/postgresql-cookbook/commit/f53c6ff76ebeedc3d18869f6c9f611cfc0ac7516

**Comment by patcon** [comment]
This is good to close now @chewi :)

**Comment by chewi** [comment]
Thank you.
